#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# ============================================================
# Task B-17 (M3): generates a TypeScript enum/union-type bundle from
# CONTRACTS.md §1's shared-enum table, for packages/ecosystem-ui (task
# F-1, not built yet -- M4) to eventually consume.
#
# The enum VALUES here are transcribed directly from CONTRACTS.md §1 --
# that markdown table is the single source of truth this script mirrors;
# if the two ever disagree, the doc is authoritative and this script is
# what's out of date, not the other way around. KnownSurface/KnownProduct
# are generated from the live ecosystem_surfaces/ecosystem_product_profiles
# seed rows instead (§1's own note: these are data-driven registries, not
# closed unions -- the generated type is for editor autocomplete only,
# runtime code must always validate against a live GET /ecosystem/config
# response, never against this generated type).
#
# Usage:
#   python scripts/ecosystem/generate_ts_enums.py           # regenerate
#   python scripts/ecosystem/generate_ts_enums.py --check   # diff, exit 1 on drift
# ============================================================

from __future__ import annotations

import os
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_OUTPUT_PATH = os.path.join(_REPO_ROOT, "scripts", "ecosystem", "generated", "ecosystem_enums.ts")

# Transcribed from docs/ecosystem/CONTRACTS.md §1 -- keep in the same
# order as that table.
_ENUMS: dict[str, list[str]] = {
    "ItemType": ["skill", "plugin", "mcp_server", "connector"],
    "ItemScope": ["builtin", "optional", "central_index", "org_private"],
    "ItemStatus": ["active", "source_unavailable", "yanked", "deprecated"],
    "TrustTier": ["builtin", "verified", "org", "community", "agent_created"],
    "GateVerdict": ["pass", "warn", "fail", "pending"],
    "GateStage": ["manifest", "license", "static_safety", "supply_chain", "sandbox", "ethics", "mcp_connector"],
    "GateSeverity": ["info", "warn", "block"],
    "InstallScope": ["private", "shared", "org", "provisioned", "required"],
    "InstallOrigin": ["created", "shared", "provisioned", "required", "added"],
    "DraftStatus": ["drafting", "ready", "submitted", "abandoned"],
    "Execution": ["server", "local"],
    "ConnectionStatus": [
        "connected", "needs_reauth", "expired", "revoked", "insufficient_scope",
        "not_connected", "connecting", "error",
    ],
    "SecretClass": ["platform", "per_user", "org_shared", "device_local"],
    "SecretBackend": ["builtin", "aws_kms", "gcp_kms", "azure_kv", "vault"],
    "JobStatus": ["verifying", "active", "warn", "blocked", "failed"],
    "ChangeKind": ["installed", "uninstalled", "enabled", "disabled", "updated", "blocked", "connection_changed"],
    "SourceKind": ["github_repo", "mcp_registry", "well_known", "private_git", "skills_sh_indirect", "local"],
    "GateTrigger": ["ui_add", "chat_create", "cli", "index_ci", "admin_provision", "desktop", "new_version"],
    "ItemTypeState": ["available", "coming_soon"],
}


def _known_registry_values() -> dict[str, list[str]]:
    """KnownSurface/KnownProduct, transcribed from db/migrate.py's
    _part_ad1_ecosystem_marketplace_tables_2026_09_25()'s own seed INSERT
    statements (5 surfaces, 2 product profiles) -- NOT queried live from a
    database. A DB-dependent generator would make this script's --check
    mode (the CI drift job, which runs in a Tier-1 static-checks job with
    no Postgres service) non-deterministic: CI would regenerate with zero
    rows (DB unreachable) and always report drift against a locally-
    generated file that has the real seed values. These two are, in
    practice, edited by hand alongside db/migrate.py's own seed rows --
    both are static seed data, not something that changes independent of
    a migration.
    """
    return {
        "KnownSurface": ["chat", "agent_studio", "cowork", "desktop", "workspace_chat"],
        "KnownProduct": ["enterprise", "workspace"],
    }


def _render(enums: dict[str, list[str]], known: dict[str, list[str]]) -> str:
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// GENERATED FILE -- do not edit by hand.",
        "// Source: docs/ecosystem/CONTRACTS.md §1, generated by scripts/ecosystem/generate_ts_enums.py.",
        "",
    ]
    for name, values in enums.items():
        union = " | ".join(f'"{v}"' for v in values)
        lines.append(f"export type {name} = {union};")
    lines.append("")
    lines.append("// Data-driven registries (CONTRACTS.md §1) -- editor-autocomplete convenience")
    lines.append("// ONLY. Runtime code must always validate against a live GET /ecosystem/config")
    lines.append("// response, never against these two.")
    for name, values in known.items():
        if values:
            union = " | ".join(f'"{v}"' for v in values)
        else:
            union = "string  /* no seed rows reachable at generation time */"
        lines.append(f"export type {name} = {union};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv
    rendered = _render(_ENUMS, _known_registry_values())

    if check_only:
        if not os.path.exists(_OUTPUT_PATH):
            print(f"MISSING: {_OUTPUT_PATH} does not exist -- run without --check to generate it.")
            return 1
        with open(_OUTPUT_PATH, encoding="utf-8") as f:
            committed = f.read()
        if committed != rendered:
            print(
                f"DRIFT: {_OUTPUT_PATH} does not match the current generator output. "
                "Run 'python scripts/ecosystem/generate_ts_enums.py' and commit the result."
            )
            return 1
        print(f"OK: {_OUTPUT_PATH} matches the current generator output.")
        return 0

    os.makedirs(os.path.dirname(_OUTPUT_PATH), exist_ok=True)
    with open(_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(rendered)
    print(f"wrote {_OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
